services:
  postgres:
    image: postgres:15
    container_name: test_postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    volumes:
#      - pgadmin-data:/data

volumes:
  postgres_data:
#  pgadmin-data:

